name: flutter_sample
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_swiper_null_safety_flutter3: ^4.0.3
  http: ^1.2.2
  image_picker: ^1.1.2
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  

flutter:
  uses-material-design: true

  assets:
  - images/2048111.jpg
  - images/204814.jpg
  - images/204815.jpg
  - images/123.jpg
  - images/22.jpg
  - images/111.jpg
  - images/1112.jpg

